# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RHEhARn7_WqSRGLsx2sVA8C3X6C_-vL

Unemployment Analysis with Python

---
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Unemployment_Rate_upto_11_2020.csv")

df.head()

df.describe()

df.info()

print(df.isnull().sum())

df.rename(columns={'Region':'State'},inplace=True)

df=df.dropna()
df=df.reset_index(drop=True)

df.columns=df.columns.str.strip()

# Unemployment rate trend over time
plt.figure(figsize=(45, 8))
sns.lineplot(x='State', y='Estimated Unemployment Rate (%)', data=df)
plt.title('Unemployment Rate Over Time')
plt.xlabel('State')
plt.ylabel('Estimated Unemployment Rate (%)')
plt.show()

#Labor Participation Rate trend over time

plt.figure(figsize=(45, 8))
sns.lineplot(x='State', y='Estimated Labour Participation Rate (%)', data=df)
plt.title('Labour Participation Rate Over Time')
plt.xlabel('State')
plt.ylabel('Estimated Labour Participation Rate (%)')
plt.show()

#Number of Employed trend over time

plt.figure(figsize=(45, 8))
sns.lineplot(x='State', y='Estimated Employed', data=df)
plt.title('Number of Employed Over Time')
plt.xlabel('State')
plt.ylabel('Estimated Employed')
plt.show()

plt.figure(figsize=(45, 8))
sns.histplot(x='State', y='Estimated Unemployment Rate (%)', data=df)
plt.title('Unemployment Rate Over Time')
plt.xlabel('State')
plt.ylabel('Estimated Unemployment Rate (%)')
plt.show()

plt.figure(figsize=(45, 8))
sns.barplot(x='State', y='Estimated Unemployment Rate (%)', data=df)
plt.title('Unemployment Rate Over Time')
plt.xlabel('State')
plt.ylabel('Estimated Unemployment Rate (%)')
plt.show()

plt.figure(figsize=(45, 8))
sns.boxplot(x='State', y='Estimated Unemployment Rate (%)', data=df)
plt.title('Unemployment Rate Over Time')
plt.xlabel('State')
plt.ylabel('Estimated Unemployment Rate (%)')
plt.show()

sns.pairplot(df[['Estimated Unemployment Rate (%)', 'Estimated Employed', 'Estimated Labour Participation Rate (%)']])
plt.show()

#selecting only numeric columns for correlation matrix
numeric_df = df.select_dtypes (include=[float, int])
correlation_matrix = numeric_df.corr()
print("\nCorrelation Matrix:")
print(correlation_matrix)

plt.figure(figsize=(8, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=1, linecolor='k')
plt.title('Correlation Matrix')
plt.show()