# -*- coding: utf-8 -*-
"""task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CJLonNJuYmiGHaFXxPfGnpY0ADxkR9RS
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/car data.csv")
print(df.head())

df.describe()

df.info()

print(df.isnull().sum())

df.replace({'Fuel_Type':{'Petrol':0,'Diesel':1,'CNG':2}},inplace=True)

df.replace({'Seller_Type':{'Dealer':0,'Individual':1}},inplace=True)

df.replace({'Transmission':{'Manual':0,'Automatic':1}},inplace=True)

df.head()

x = df.drop(['Car_Name','Selling_Price'],axis=1)
y = df['Selling_Price']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,random_state=2)

from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import LabelEncoder
Numerics = LabelEncoder()

for column in x.select_dtypes(include=['object']).columns:
    x[column] = Numerics.fit_transform(x[column])

from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(x,y)

df

x = df.drop(['Selling_Price'], axis=1)
target = df['Selling_Price']

inputs_n = x.select_dtypes(include=['int64', 'float64']).copy()

model.fit(inputs_n, target)

pred = model.predict(inputs_n.iloc[[0]])
print(pred)

Car_Price = model.predict(inputs_n)

from sklearn import metrics

plt.scatter(target, Car_Price)
plt.xlabel("Actual price")
plt.ylabel("Prediction price")
plt.title("Actual price vs Prediction price")
plt.show()