# -*- coding: utf-8 -*-
"""task_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9TySJWuqkNX0tNyxUUdv9s6GyT9GbtG
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/spam.csv", encoding='latin-1')
print(df.head())

df.info()

df.columns

df.describe()

df.isnull().sum()

df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
df

sns.countplot(df['v1'])
plt.show()

plt.pie(df['v1'].value_counts(), labels=['ham', 'spam'], autopct='%1.1f%%')
plt.show()

x_train, x_test, y_train, y_test = train_test_split(df['v2'], df['v1'], test_size=0.2, random_state=42)

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix

vectorizer = CountVectorizer()
x_train_vectorized = vectorizer.fit_transform(x_train)
x_test_vectorized = vectorizer.transform(x_test)

classifier = MultinomialNB()
classifier.fit(x_train_vectorized, y_train)

y_pred = classifier.predict(x_test_vectorized)

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion_matrix)