# -*- coding: utf-8 -*-
"""task_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eRXF7rmCj7e8GFNCVG9gSfz0cFIM-QVV

## SALES PREDICTION USING PYTHON
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Advertising.csv")
print(df.head())

df.head()

df.info()

df.describe()

df

df.isnull().sum()

x=df.drop('Sales',axis=1)
y=df['Sales']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

x_train

y_train

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

sns.pairplot(df,x_vars=['TV','Radio','Newspaper'],y_vars='Sales',height=4,aspect=1,kind='scatter')
plt.show()

sns.histplot(df['Sales'],kde=True)
plt.show()